library(pwr)
pwr.t.test(d = 0.8, sig.level =0.05, power =.8 )
#d is effect size, and power is how certain you want to be
pwr.t.test(d = 0.5, sig.level =0.05, power =.8 )
#if you think the effect is small, you need to be more certain
#we basically just make up these numbers because we don't really know

#we can also change the parameters to see how underpowered we will be
#given realistic sample sizes
pwr.t.test(n=10,d = 0.5, sig.level =0.05)
#this isn't great - we have pretty small power
pwr.t.test(n=20,d = 0.5, sig.level =0.05)

##see this for more info
#https://www.statmethods.net/stats/power.html

##example of power analysis simulation##
#I want to run an experiment where I have experimentally infect birds with a bacteria
#and then examine their behavior in relation to untreated birds. 
#I'm trying to figure out how many birds I might need for my experiment. 

# My question is how do demographics and infection influence that amount of time a bird spends eating?
#possible demographic categories: ym=young male, om=old male, yf=young female, of=old female
# treatment: infected/control
#time spent eating: seconds, drawn from a normal distribution
# parameter to vary - number in each group

#set up my unique groups of interest
demog = c("ym","om","yf","of")
inf = c("treat","control")

#set aside space for results
dat.save = NA
dat.now = NA

#create a "for" loop to consider possibilities for sample sizes (can have as many as I want)
sample.size = c(5,10,15,20,25,30)

for( i in 1:length(sample.size)) {#this says go through this sim for each of the unique possible sample sizes
#create a dataframe that is all of my unique predictor variables replicated by the sample size I want to explore
  dat.now = expand.grid(demog=rep(demog,times=1, each=sample.size[i]), 
                      inf=rep(inf, times=1, each=sample.size[i]))

#generate possible data for controls - drawing from a normal
dat.now$eat.time[dat.now$demog=="ym"& dat.now$inf=="control"] = rnorm(sample.size[i], mean=5, sd=2)
dat.now$eat.time[dat.now$demog=="om"& dat.now$inf=="control"] = rnorm(sample.size[i], mean=7, sd=2)
dat.now$eat.time[dat.now$demog=="of"& dat.now$inf=="control"] = rnorm(sample.size[i], mean=4, sd=2)
dat.now$eat.time[dat.now$demog=="yf"& dat.now$inf=="control"] = rnorm(sample.size[i], mean=4.5, sd=2)

#generate possible data for infecteds - drawing from a normal
dat.now$eat.time[dat.now$demog=="ym"& dat.now$inf=="treat"] = rnorm(sample.size[i], mean=10, sd=1.2)
dat.now$eat.time[dat.now$demog=="om"& dat.now$inf=="treat"] = rnorm(sample.size[i], mean=8, sd=1.2)
dat.now$eat.time[dat.now$demog=="of"& dat.now$inf=="treat"] = rnorm(sample.size[i], mean=6.6, sd=1.2)
dat.now$eat.time[dat.now$demog=="yf"& dat.now$inf=="treat"] = rnorm(sample.size[i], mean=7, sd=1.2)

#add the sample size I am testing to the dataframe
dat.now$N = sample.size[i]

#since dat.now will be re-written at each iteration, save it in a combined dataframe belw
dat.save = rbind(dat.now, dat.save)
}

print(i)
head(dat.now)
head(dat.save)
tail(dat.save)

#compare my lms

#5 birds per group
l5 = lm(eat.time ~ demog*inf, data = dat.save, subset=N==5) #run an lm - examine sig diffs for just the groupings of 5 birds
#10 birds
l10 = lm(eat.time ~ demog*inf, data = dat.save, subset=N==10) #run an lm - examine sig diffs for just the groupings of 10 birds
#15 birds
l15 = lm(eat.time ~ demog*inf, data = dat.save, subset=N==15)
#20 birds
l20 = lm(eat.time ~ demog*inf, data = dat.save, subset=N==20)
#25 birds
l25 = lm(eat.time ~ demog*inf, data = dat.save, subset=N==25)
#30 birds
l30 = lm(eat.time ~ demog*inf, data = dat.save, subset=N==30)

summary(l5)
summary(l10)
summary(l15)
summary(l30)

#if you want full list of pairwise, like might be generated by emmeans need to do this...
dat.save.5 = subset(dat.save, N==5)
l5 = lm(eat.time ~ demog*inf, data = dat.save.5) #run an lm - examine sig diffs for just the groupings of 5 birds
l5.em = emmeans(l5, pairwise ~ demog*inf)
plot.5 = plot(l5.em)

#sample size of 10
dat.save.10 = subset(dat.save, N==10)
l10 = lm(eat.time ~ demog*inf, data = dat.save.10) #run an lm - examine sig diffs for just the groupings of 5 birds
l10.em = emmeans(l10, pairwise ~ demog*inf)
plot.10 = plot(l10.em)


#sample size of 15
dat.save.15 = subset(dat.save, N==15)
l15 = lm(eat.time ~ demog*inf, data = dat.save.15) #run an lm - examine sig diffs for just the groupings of 5 birds
l15.em = emmeans(l15, pairwise ~ demog*inf)
plot.15 = plot(l15.em)

library(cowplot)
sample.comparisons<-plot_grid(plot.5,plot.10, plot.15, ncol = 1, labels=c('5 birds', '10 birds','15 birds'),hjust = 0, label_x =.07,rel_heights = c(1/2,1/2,1/2))

sample.comparisons
